import { NextResponse } from "next/server";
import PDFDocument from "pdfkit";
import { createRouteSupabase } from "@/lib/supabase/server";
import { z } from "zod";

export const runtime = "nodejs";

const Invoice = z.object({
  id: z.string(),
  number: z.string().nullish(),
  status: z.string().nullish(),
  issued_at: z.string().nullish(),
  due_date: z.string().nullish(),
  total_amount: z.union([z.number(), z.string()]).nullish(),
  currency: z.string().nullish(),
  description: z.string().nullish(),
});

type InvoiceRow = z.infer<typeof Invoice>;

function fmtCurrency(amount: number, currency: string | null | undefined) {
  const cur = currency ?? "PKR";
  try {
    return new Intl.NumberFormat("en-GB", {
      style: "currency",
      currency: cur,
      maximumFractionDigits: 2,
    }).format(amount);
  } catch {
    return `${amount.toFixed(2)} ${cur}`;
  }
}

function fmtDate(s: string | null | undefined) {
  if (!s) return "—";
  const d = new Date(s);
  if (Number.isNaN(d.getTime())) return "—";
  return d.toLocaleDateString("en-GB", {
    year: "numeric",
    month: "short",
    day: "2-digit",
  });
}

export async function GET(
  _req: Request,
  { params }: { params: { id: string } }
) {
  const supabase = createRouteSupabase();
  const { id } = params;

  const { data, error } = await supabase
    .from("invoices")
    .select(
      "id, number, status, issued_at, due_date, total_amount, currency, description"
    )
    .eq("id", id)
    .maybeSingle();

  if (error || !data) {
    return NextResponse.json(
      { error: error?.message ?? "Invoice not found" },
      { status: 404 }
    );
  }

  let invoice: InvoiceRow;
  try {
    invoice = Invoice.parse(data);
  } catch {
    return NextResponse.json({ error: "Invoice shape unexpected" }, { status: 500 });
  }

  const amount =
    typeof invoice.total_amount === "string"
      ? Number.parseFloat(invoice.total_amount)
      : invoice.total_amount ?? 0;

  const amountSafe = Number.isFinite(amount) ? amount : 0;
  const amountPretty = fmtCurrency(amountSafe, invoice.currency);

  // --- Build PDF in-memory (with header/footer) ---
  const doc = new PDFDocument({ size: "A4", margin: 48 });
  const chunks: Buffer[] = [];
  doc.on("data", (c) => chunks.push(c));
  const done: Promise<Buffer> = new Promise((resolve) =>
    doc.on("end", () => resolve(Buffer.concat(chunks)))
  );

  // Header
  doc
    .fontSize(18)
    .text("RENTBACK", { continued: false, align: "left" })
    .moveDown(0.25);
  doc
    .fontSize(12)
    .fillColor("#6B7280")
    .text("Invoice", { align: "left" })
    .moveDown(0.25);
  doc
    .moveTo(48, doc.y + 4)
    .lineTo(547, doc.y + 4)
    .strokeColor("#E5E7EB")
    .stroke()
    .moveDown();

  // Meta
  doc.fillColor("#111827").fontSize(11);
  doc.text(`Invoice #: ${invoice.number ?? invoice.id}`);
  doc.text(`Status: ${(invoice.status ?? "").toUpperCase() || "—"}`);
  doc.text(`Issued: ${fmtDate(invoice.issued_at)}`);
  doc.text(`Due:    ${fmtDate(invoice.due_date)}`).moveDown();

  // Description
  doc.fontSize(12).text("Description:", { underline: false }).moveDown(0.25);
  doc
    .fontSize(11)
    .fillColor("#374151")
    .text(invoice.description ?? "Rent charge")
    .moveDown();

  // Total
  doc
    .fillColor("#111827")
    .fontSize(12)
    .text("Total", { continued: true })
    .text(`  ${amountPretty}`, { align: "left" })
    .moveDown();

  // Footer
  const addFooter = () => {
    const bottom = 780;
    doc
      .fontSize(9)
      .fillColor("#6B7280")
      .text("Generated by RentBack", 48, bottom, { align: "left" });
    doc
      .fontSize(9)
      .fillColor("#6B7280")
      .text(`Page ${doc.page.number}`, 48, bottom, { align: "right" });
  };
  addFooter();

  doc.end();

  const pdfBuffer = await done;
  const arrayBuffer = pdfBuffer.buffer.slice(
    pdfBuffer.byteOffset,
    pdfBuffer.byteOffset + pdfBuffer.byteLength
  ) as ArrayBuffer;

  return new NextResponse(arrayBuffer, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `inline; filename="invoice-${
        invoice.number ?? invoice.id
      }.pdf"`,
      "Cache-Control": "no-store",
    },
  });
}
