// app/api/tenant/invoices/[id]/receipt/route.ts
import { NextResponse } from "next/server";
import PDFDocument from "pdfkit";
import { createRouteSupabase } from "@/lib/supabase/server";

export const runtime = "nodejs";

function formatMoney(amount?: number, currency?: string) {
  const cur = currency || "PKR";
  const num = typeof amount === "number" ? amount : 0;
  try {
    return new Intl.NumberFormat("en-PK", { style: "currency", currency: cur }).format(num);
  } catch {
    return `${cur} ${num.toLocaleString()}`;
  }
}

export async function GET(
  _req: Request,
  { params }: { params: { id: string } }
) {
  const supabase = createRouteSupabase();

  const { data: invoice, error } = await supabase
    .from("invoices")
    .select(
      [
        "id",
        "number",
        "status",
        "amount",
        "currency",
        "due_date",
        "issued_at",
        "paid_at",
        "landlord_name",
        "landlord_email",
        "tenant_email"
      ].join(",")
    )
    .eq("id", params.id)
    .single();

  if (error || !invoice) {
    return NextResponse.json({ error: "Invoice not found" }, { status: 404 });
  }

  if (String(invoice.status).toLowerCase() !== "paid") {
    return NextResponse.json(
      { error: "Receipt is only available for PAID invoices" },
      { status: 409 }
    );
  }

  const doc = new PDFDocument({ size: "A4", margin: 50 });
  const chunks: Buffer[] = [];
  doc.on("data", (c) => chunks.push(Buffer.isBuffer(c) ? c : Buffer.from(c)));
  const done = new Promise<void>((res) => doc.on("end", () => res()));

  // Header / brand
  doc
    .fontSize(18)
    .fillColor("#065f46")
    .text("RentBack — Receipt");
  doc.moveDown(0.5);
  doc
    .fontSize(10)
    .fillColor("#111827")
    .text(`Invoice #${invoice.number ?? invoice.id}`);
  doc.text(`Paid: ${invoice.paid_at ? new Date(invoice.paid_at).toDateString() : "—"}`);
  doc.moveDown();

  // Parties
  doc.fontSize(12).fillColor("#111827").text("Paid By:");
  doc.fontSize(10).text(invoice.tenant_email ?? "—");
  doc.moveDown(0.5);

  doc.fontSize(12).text("Received By:");
  doc.fontSize(10).text(invoice.landlord_name || invoice.landlord_email || "—");
  doc.moveDown();

  // Amount
  const total = formatMoney(invoice.amount, invoice.currency);
  doc
    .fontSize(14)
    .fillColor("#111827")
    .text("Amount Paid", { continued: true })
    .fillColor("#065f46")
    .text(`   ${total}`);
  doc.moveDown();

  // Footer
  doc
    .fontSize(9)
    .fillColor("#6b7280")
    .text("Receipt generated by RentBack.");
  doc.end();

  await done;
  const pdf = Buffer.concat(chunks);

  return new NextResponse(pdf, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `inline; filename="receipt-${invoice.number ?? invoice.id}.pdf"`
    }
  });
}
